# -*- coding: utf-8 -*-
"""FINAL_ nlp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vux2psUXHGYkSzpLdTpoJMazxU55ANj6
"""

!pip install -q transformers datasets evaluate rouge-score
!pip install -q bitsandbytes
!pip install evaluate

import torch
import bitsandbytes as bnb
print("bitsandbytes loaded")

!pip install -U transformers

import transformers
print(transformers.__version__)

import torch
import re
import pandas as pd

from datasets import Dataset
from transformers import (
    T5Tokenizer,
    T5ForConditionalGeneration,
    TrainingArguments,
    Trainer,
    BitsAndBytesConfig
)

from peft import LoraConfig, get_peft_model
import evaluate

df = pd.read_csv("Reviews.csv")

df = df[['Text', 'Summary', 'Score']]   # ← keep Score

df.rename(
    columns={'Text': 'reviewText', 'Summary': 'summary'},
    inplace=True
)

df.dropna(inplace=True)

df = df.sample(n=10000, random_state=42).reset_index(drop=True)

print(df.head())
print(df.columns)

def clean_text(text):
    text = text.lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"<.*?>", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

df['reviewText'] = df['reviewText'].apply(clean_text)
df['summary'] = df['summary'].apply(clean_text)

dataset = Dataset.from_pandas(df)
dataset = dataset.train_test_split(test_size=0.2, seed=42)

train_ds = dataset["train"]
test_ds = dataset["test"]

tokenizer = T5Tokenizer.from_pretrained("t5-small")

MAX_INPUT = 256
MAX_TARGET = 64

def preprocess(batch):
    model_inputs = tokenizer(
        ["summarize: " + t for t in batch["reviewText"]],
        max_length=MAX_INPUT,
        truncation=True,
        padding="max_length"
    )

    labels = tokenizer(
        text_target=batch["summary"],
        max_length=MAX_TARGET,
        truncation=True,
        padding="max_length"
    )

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

train_ds = train_ds.map(preprocess, batched=True, remove_columns=train_ds.column_names)
test_ds = test_ds.map(preprocess, batched=True, remove_columns=test_ds.column_names)

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True
)

model = T5ForConditionalGeneration.from_pretrained(
    "t5-small",
    quantization_config=bnb_config,
    device_map="auto"
)

lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    lora_dropout=0.05,
    bias="none",
    task_type="SEQ_2_SEQ_LM",
    target_modules=["q", "v"]
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

training_args = TrainingArguments(
    output_dir="./t5_qlora",
    per_device_train_batch_size=2,
    gradient_accumulation_steps=4,
    learning_rate=2e-4,
    num_train_epochs=2,
    logging_steps=100,
    report_to="none",
    fp16=True
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_ds
)

trainer.train()

trainer.save_model("./t5_qlora_model")
tokenizer.save_pretrained("./t5_qlora_model")

model.eval()

# Take 10 random reviews
sample_df = df.sample(n=10).reset_index(drop=True)

for i in range(10):
    review = sample_df.loc[i, "reviewText"]
    true_summary = sample_df.loc[i, "summary"]   # dataset summary

    inputs = tokenizer(
        "summarize: " + review,
        return_tensors="pt",
        truncation=True,
        max_length=256
    ).to(model.device)

    with torch.no_grad():
        output = model.generate(
            **inputs,
            max_length=60,
            min_length=15,
            num_beams=6,
            length_penalty=1.2,
            no_repeat_ngram_size=3,
            early_stopping=True
        )

    generated_summary = tokenizer.decode(
        output[0],
        skip_special_tokens=True
    )

    print(f" REVIEW {i+1}")
    print("Review Text:")
    print(review[:500], "..." if len(review) > 500 else "")

    print("\nOriginal Summary (Dataset):")
    print(true_summary)

    print("\nModel Generated Summary:")
    print(generated_summary)
    print("=" * 80)

# store summaries
generated_data = []

for i in range(len(df)):
    review = df.loc[i, "reviewText"]

    inputs = tokenizer(
        "summarize: " + review,
        return_tensors="pt",
        truncation=True,
        max_length=256
    ).to(model.device)

    with torch.no_grad():
        output = model.generate(
            **inputs,
            max_length=60
        )

    summary = tokenizer.decode(output[0], skip_special_tokens=True)

    generated_data.append(summary)

df["generated_summary"] = generated_data

from transformers import BertTokenizer, BertModel

bert_tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
bert_model = BertModel.from_pretrained("bert-base-uncased")
bert_model.eval()

for param in bert_model.parameters():
    param.requires_grad = False

def get_bert_embeddings_batch(texts, max_len=128):
    inputs = bert_tokenizer(
        texts,
        padding=True,
        truncation=True,
        max_length=max_len,
        return_tensors="pt"
    )

    with torch.no_grad():
        outputs = bert_model(**inputs)

    return outputs.last_hidden_state

import torch
import torch.nn as nn

class TransformerBlock(nn.Module):
    def __init__(self, embed_dim, num_heads, ff_dim):
        super().__init__()
        self.attn = nn.MultiheadAttention(
            embed_dim, num_heads, batch_first=True
        )
        self.ff = nn.Sequential(
            nn.Linear(embed_dim, ff_dim),
            nn.ReLU(),
            nn.Linear(ff_dim, embed_dim)
        )
        self.norm1 = nn.LayerNorm(embed_dim)
        self.norm2 = nn.LayerNorm(embed_dim)

    def forward(self, x):
        attn_out, _ = self.attn(x, x, x)
        x = self.norm1(x + attn_out)
        ff_out = self.ff(x)
        x = self.norm2(x + ff_out)
        return x

class BiGRUEncoder(nn.Module):
    def __init__(self, input_dim, hidden_dim):
        super().__init__()
        self.bigru = nn.GRU(
            input_dim,
            hidden_dim,
            batch_first=True,
            bidirectional=True
        )

    def forward(self, x):
        outputs, hidden = self.bigru(x)
        return outputs, hidden

class Attention(nn.Module):
    def __init__(self, enc_dim, dec_dim):
        super().__init__()
        self.attn = nn.Linear(enc_dim + dec_dim, dec_dim)
        self.v = nn.Linear(dec_dim, 1, bias=False)

    def forward(self, hidden, encoder_outputs):
        seq_len = encoder_outputs.size(1)
        hidden = hidden.unsqueeze(1).repeat(1, seq_len, 1)
        energy = torch.tanh(
            self.attn(torch.cat((hidden, encoder_outputs), dim=2))
        )
        attention = self.v(energy).squeeze(2)
        return torch.softmax(attention, dim=1)

class GRUDecoder(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super().__init__()
        self.gru = nn.GRU(input_dim, hidden_dim, batch_first=True)
        self.fc = nn.Linear(hidden_dim, output_dim)

    def forward(self, x, hidden):
        output, _ = self.gru(x, hidden)
        return self.fc(output[:, -1, :])

class SummaryRatingModel(nn.Module):
    def __init__(self, embed_dim, hidden_dim, num_classes):
        super().__init__()

        self.transformer = TransformerBlock(embed_dim, 4, 256)
        self.encoder = BiGRUEncoder(embed_dim, hidden_dim)
        self.attention = Attention(hidden_dim * 2, hidden_dim)
        self.decoder = GRUDecoder(hidden_dim * 2, hidden_dim, num_classes)

    def forward(self, x):
        x = self.transformer(x)
        enc_out, hidden = self.encoder(x)

        hidden = hidden[-1]
        attn_weights = self.attention(hidden, enc_out)
        context = torch.bmm(attn_weights.unsqueeze(1), enc_out)

        return self.decoder(context, hidden.unsqueeze(0))

class SummaryDataset(Dataset):
    def __init__(self, summaries, labels):
        self.summaries = summaries
        self.labels = labels

    def __len__(self):
        return len(self.summaries)

    def __getitem__(self, idx):
        return self.summaries[idx], self.labels[idx]

print(df.columns)

from torch.utils.data import Dataset

class SummaryDataset(Dataset):
    def __init__(self, summaries, labels):
        self.summaries = summaries          # list of strings
        self.labels = labels                # list of ints

    def __len__(self):
        return len(self.summaries)

    def __getitem__(self, idx):
        return self.summaries[idx], self.labels[idx]

labels = (df["Score"].values - 1).tolist()

from torch.utils.data import DataLoader

dataset = SummaryDataset(
    df["generated_summary"].astype(str).tolist(),
    labels
)

loader = DataLoader(
    dataset,
    batch_size=8,
    shuffle=True
)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

rating_model = SummaryRatingModel(
    embed_dim=768,
    hidden_dim=128,
    num_classes=5
).to(device)

optimizer = torch.optim.Adam(rating_model.parameters(), lr=1e-4)
criterion = torch.nn.CrossEntropyLoss()

for epoch in range(10):
    rating_model.train()
    total_loss = 0

    for summaries, labels in loader:
        optimizer.zero_grad()

        embeddings = get_bert_embeddings_batch(summaries).to(device)
        labels = labels.to(device).long()

        outputs = rating_model(embeddings)
        loss = criterion(outputs, labels)

        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1} Loss: {total_loss/len(loader):.4f}")

rating_model.eval()

correct = 0
total = 0

with torch.no_grad():
    for summaries, labels in loader:
        embeddings = get_bert_embeddings_batch(summaries).to(device)
        labels = labels.to(device).long()

        outputs = rating_model(embeddings)
        preds = torch.argmax(outputs, dim=1)

        correct += (preds == labels).sum().item()
        total += labels.size(0)

overall_accuracy = correct / total
print(f"Overall Accuracy: {overall_accuracy * 100:.2f}%")

import evaluate

# load rouge metric
rouge = evaluate.load("rouge")

# convert dataframe columns to list
predictions = df["generated_summary"].tolist()
references  = df["summary"].tolist()

# compute rouge
results = rouge.compute(
    predictions=predictions,
    references=references,
    use_stemmer=True
)

print("ROUGE Scores:")
for key, value in results.items():
    print(f"{key}: {value:.4f}")

rating_model.eval()

import random

# take 10 random samples
sample_df = df.sample(n=10).reset_index(drop=True)

print("\n SAMPLE RATING PREDICTIONS \n")

for i in range(len(sample_df)):

    review_text = sample_df.loc[i, "reviewText"]
    summary = sample_df.loc[i, "generated_summary"]
    true_rating = sample_df.loc[i, "Score"]

    # Get BERT embedding of summary
    embedding = get_bert_embeddings_batch([summary]).to(device)

    with torch.no_grad():
        output = rating_model(embedding)
        pred_class = torch.argmax(output, dim=1).item()

    predicted_rating = pred_class + 1   # because labels were 0–4

    print(f"Review {i+1}")
    print("Review Text:", review_text[:200], ".." if len(review_text)>200 else "")
    print("Generated Summary:", summary)
    print("True Rating:", true_rating)
    print("Predicted Rating:", predicted_rating)
    print("-"*60)